name: Publish

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Get Branch Name
        shell: bash
        run: echo "::set-output name=name::$(bash scripts/branchname.sh)"
        id: branch

      - name: Setup
        run: npm install

      - name: Build Documentation
        run: npm run build

      - name: Deploy to Github Pages
        id: deploy_step
        if: steps.branch.outputs.name == 'master'
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: gh-pages
          keep_history: true
          build_dir: docs
        env:
          GH_PAT: ${{ secrets.DOCBOT_GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.DOCBOT_GH_PAT }}

      - name: Send Failure notification to Slack
        if: always() && steps.deploy_step.outcome == 'failure'
        run: npm run info_slack_failure 
        env:
            SLNL: ${{ secrets.SLNL }}  

      - name: Send Success notification to Slack
        if: always() && steps.deploy_step.outcome == 'success'
        run: npm run info_slack_success 
        env:
            SLNL: ${{ secrets.SLNL }}  
