name: Publish

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup
      run: npm install

    - name: Build Documentation
      run: npm run build

    # - name: Deploy to Github Pages
    #   uses: crazy-max/ghaction-github-pages@v2.1.2
    #   with:
    #     target_branch: gh-pages
    #     keep_history: true
    #     build_dir: docs
    #   env:
    #     GH_PAT: ${{ secrets.DOCBOT_GH_PAT }}
    